### ISSUE TITLE
Ruby 2.4.0 compatibility

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#94]
Not a problem with ruby-vips per se. However, the glib2 3.0.8 gem no longer builds under Ruby 2.4.0 whereas the glib2 3.0.9 builds just fine.

The issue appears to be that glib2 3.0.8 uses `rb_cFixnum` which no longer exists in MRI and has been replace with `rb_cInteger` (see https://bugs.ruby-lang.org/issues/12005).

I've looked at the glib2 ruby project and 3.0.8 is now two releases behind so my guess is there'll be close to no motivation for them to want to fix the issue.

Is there something I can do to help bring ruby-vips up to the latest glib2 or is that a massive undertaking?

Alternatively, I suppose we could for glib2 at 3.0.8 and patch it but that's not ideal.

**Comment by jcupitt** [comment]
Hi, yes, I remember running into this problem, it's frustrating. When I last looked, there didn't seem to be a simple solution for ruby-vips, but perhaps things have moved on.

I'll try to investigate!

**Comment by jcupitt** [comment]
It looks like the worst problems have vanished, it was pretty easy to make it sort-of work with glib2 3.1.1:

https://github.com/jcupitt/ruby-vips/tree/move-to-goi-3.1

There are four failure in the test suite, all related to fixnum (as you said). They look something like:

```
$ rake
Resolving dependencies...
/usr/bin/ruby2.3 -I/home/john/packages/gems/gems/rspec-core-3.5.4/lib:/home/john/packages/gems/gems/rspec-support-3.5.0/lib /home/john/packages/gems/gems/rspec-core-3.5.4/exe/rspec spec/image_spec.rb spec/vips_spec.rb
...FF.....FF.....................................

Failures:

  1) Vips::Image can save an image to a buffer
     Failure/Error: value = value.pack("C*")

     NoMethodError:
       undefined method `pack' for 255:Fixnum
     # ./lib/vips/argument.rb:114:in `block in unwrap'
```

They need looking into.

**Comment by jcupitt** [comment]
OK, the test suite runs cleanly now, I found a couple more small differences.

That's with ruby2.3, would you be able to test with 2.4?

**Comment by harukizaemon** [comment]
Sorry, was away. Will try it out now.

**Comment by harukizaemon** [comment]
Looks good to me?

```
❯ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

❯ bundle
Resolving dependencies...
Using rake 11.3.0
Using bundler 1.13.7
Using diff-lcs 1.3
Using github-markup 1.4.1
Using pkg-config 1.1.7
Using redcarpet 3.4.0
Using rspec-support 3.5.0
Using yard 0.9.8
Using glib2 3.1.1
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using gobject-introspection 3.1.1
Using rspec 3.5.0
Using ruby-vips 1.0.4 from source at `.`
Bundle complete! 7 Gemfile dependencies, 15 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

❯ bundle exec rake
/usr/local/Cellar/ruby/2.4.0/bin/ruby -I/usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib:/usr/local/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec spec/image_spec.rb spec/vips_spec.rb
.................................................

Finished in 0.93703 seconds (files took 0.15374 seconds to load)
49 examples, 0 failures
```

**Comment by jcupitt** [comment]
That's great, thanks very much!

I'll merge to master and update the gem.

**Comment by jcupitt** [comment]
OK, all done, we have a 1.0.4 gem. Thanks again!
